-- The encrypted store behind the `agent.prompt` pointer.
--
-- Nothing in here is readable with database access alone: every secret column
-- holds an AES-256-GCM envelope whose additional-authenticated-data binds the
-- row's own identity. Move a ciphertext to another row and it stops opening.
--
-- Statements are separated by a line containing only `--> break`. The migration
-- runner splits on that rather than on `;`, so a future migration can contain a
-- function body without the splitter guessing wrong.

create table if not exists capsule_prompt (
  -- The public pointer. This value is written into the ENS `agent.prompt`
  -- record, so it is world-readable and is NOT a bearer token: possession of a
  -- ref grants nothing. Authorisation is the signature check at the edge.
  ref           text primary key,

  -- The capsule this prompt belongs to, e.g. "analyst.capsulefleet.eth".
  -- Reads MUST be scoped by (ref, capsule_name). Because refs are public, a ref
  -- alone would let any agent fetch any other agent's prompt.
  capsule_name  text not null,

  -- v1.<iv>.<tag>.<ciphertext>, base64url. AAD is
  -- "capsule_prompt:<ref>:<capsule_name>".
  body_sealed   text not null,

  -- Which master key sealed this row. Single-valued today; the column exists so
  -- rotation is a migration rather than a redesign.
  key_version   integer not null default 1,

  created_at    timestamptz not null default now()
);

--> break

-- Prompts are append-only, so this is the "what does this capsule currently
-- have" lookup, and the ordering column for the fleet view.
create index if not exists capsule_prompt_by_name
  on capsule_prompt (capsule_name, created_at desc);

--> break

-- One agent EOA per capsule. Generated by the provisioner, handed to a Fly
-- machine as an env var, and kept here so a machine can be recreated without
-- re-minting the name.
--
-- This key is the least privileged in the system: it can write exactly one text
-- record on exactly one name. That is deliberate — see CapsuleMinter.sol.
create table if not exists capsule_agent (
  capsule_name   text primary key,

  -- Public. Stored plainly because it is written to the chain at mint time and
  -- because the provisioner needs to compare it without decrypting anything.
  agent_address  text not null,

  -- v1 envelope. AAD is "capsule_agent:<capsule_name>:<agent_address>", so the
  -- key cannot be detached from the address it belongs to.
  key_sealed     text not null,

  key_version    integer not null default 1,

  created_at     timestamptz not null default now()
);
